--删除事故信息
DELETE FROM [dbo].[TB_ETMS_ACCD_ABN_EQUIP]
GO

DELETE FROM [dbo].[TB_ETMS_ACCD_DUTY_TIME] 
GO

DELETE FROM [dbo].[TB_ETMS_ACCD_ABN_OPERATION] 
GO

DELETE FROM [dbo].[TB_ETMS_ACCD_ABNORMAL]
GO

--删除值班信息
DELETE FROM TB_ETMS_DUTY_CHECK
GO
DELETE FROM TB_ETMS_DUTY_PROMPT 
GO
update tb_etms_duty_record set WARN_ID = null
go 
DELETE FROM TB_ETMS_DUTY_WARNING
GO
DELETE FROM TB_ETMS_DUTY_PATROL_TIME 
GO
DELETE FROM TB_ETMS_DUTY_RECORD 
GO
DELETE FROM TB_ETMS_DUTY_STAFF_ON_DUTY 
GO
DELETE FROM TB_ETMS_DUTY_DUTY 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_CHECK , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_PROMPT , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_RECORD , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_STAFF_ON_DUTY , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_WARNING , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_DUTY , RESEED , 0) 
GO
--删除排班规则
DELETE FROM TB_ETMS_DUTY_RULE_ITEM 
GO
DELETE FROM TB_ETMS_DUTY_SCHEDULE
GO
DELETE FROM TB_ETMS_DUTY_SCHEDULE_RULE 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_RULE_ITEM , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_SCHEDULE , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_DUTY_SCHEDULE_RULE , RESEED , 0) 
GO
--删除检修数据
DELETE FROM TB_ETMS_REPAIR_RECORD_PERSON
GO
DELETE FROM TB_ETMS_REPAIR_RECORD_EQUIP 
GO
DELETE FROM TB_ETMS_REPAIR_RECORD_ITEM 
GO
DELETE FROM TB_ETMS_REPAIR_RECORD 
GO
DELETE FROM TB_ETMS_REPAIR_CARD
GO
DELETE FROM TB_ETMS_REPAIR_CYCLE_CELL 
GO
DELETE FROM TB_ETMS_REPAIR_CYCLE
GO

--清除技术安全  

DELETE From [TB_ETMS_TECH_ACCIDENT_H]
GO
DBCC CHECKIDENT (TB_ETMS_TECH_ACCIDENT_H , RESEED , 0) 
GO
DELETE From [TB_ETMS_TECH_ACCIDENT]
GO
DBCC CHECKIDENT (TB_ETMS_TECH_ACCIDENT , RESEED , 0) 
GO

--清除留守数据
DELETE FROM dbo.TB_ETMS_STAY_DETAIL_PERSON
GO 
 DELETE FROM dbo.TB_ETMS_STAY_DETAIL
GO 
DELETE FROM dbo.TB_ETMS_STAY_SECTION_PERSON
GO 
DELETE FROM dbo.TB_ETMS_STAY_SECTION
GO 
DELETE FROM dbo.TB_ETMS_STAY_PERIOD
GO 
DELETE FROM dbo.TB_ETMS_STAY_RULE
GO 
DBCC CHECKIDENT (TB_ETMS_STAY_DETAIL , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_STAY_SECTION , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_STAY_PERIOD , RESEED , 0) 
GO
DBCC CHECKIDENT (TB_ETMS_STAY_RULE , RESEED , 0) 
GO 

--清理所有的流程实例
DELETE FROM [dbo].[JBPM_COMMENT]
GO
DELETE FROM [dbo].[JBPM_LOG]
GO
DELETE FROM [dbo].[JBPM_VARIABLEINSTANCE]
GO
DELETE FROM [dbo].[JBPM_TASKINSTANCE]
GO
DELETE FROM [dbo].[JBPM_SWIMLANEINSTANCE] 
GO
DELETE FROM [dbo].[JBPM_TOKENVARIABLEMAP]
GO
DELETE FROM [dbo].[JBPM_MODULEINSTANCE]
GO
update JBPM_TOKEN set PROCESSINSTANCE_=null
go
DELETE from [JBPM_JOB]
go
DELETE FROM [dbo].[JBPM_PROCESSINSTANCE] 
GO
DELETE FROM [dbo].[JBPM_TOKEN]
GO

