/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package gov.abrs.etms.action.workflow;

import gov.abrs.etms.action.util.BaseAction;
import gov.abrs.etms.model.baseinfo.Person;
import gov.abrs.etms.service.security.SecurityService;
import gov.abrs.etms.service.workflow.WorkFlowService;

import java.util.List;

import javax.servlet.ServletContext;

import org.apache.struts2.ServletActionContext;
import org.jbpm.graph.exe.ProcessInstance;
import org.springframework.beans.factory.annotation.Autowired;

import com.opensymphony.xwork2.Action;

public class TaskDetailAction extends BaseAction {
	private static final long serialVersionUID = 932755611515552540L;
	private String id;
	private List<String> comments;
	private ProcessInstance pi;
	private String button;
	private String desc;
	private boolean canExecute = false;
	private Person curUser;

	@Override
	public Person getCurUser() {
		return curUser;
	}

	@Override
	public String execute() throws Exception {
		curUser = securityService.getCurUser();
		pi = workFlowService.getProcessInstance(id);
		comments = workFlowService.getComments(pi);
		desc = workFlowService.getProcessInstanceDesc(pi);
		button = this.getButton(pi, curUser);
		if (!pi.hasEnded()) {
			if (workFlowService.hasActiveTaskInstance(pi, curUser)) {
				canExecute = true;
			}
		}
		return Action.SUCCESS;
	}

	private String getButton(ProcessInstance pi, Person person) {
		ServletContext context = ServletActionContext.getServletContext();
		String proccessName = pi.getProcessDefinition().getName();
		String url = "";
		String title = "";
		String button = "";
		if (proccessName.equals("事故上报流程")) {
			title = "详细信息";
			url = context.getContextPath() + "/abnormal/abnormal!detail.ajax?id=" + pi.getKey();
			button = "<a ztype=\"popUp\"  title=\""
					+ title
					+ "\" url=\""
					+ url
					+ "\" zwidth=\"950\" zheight=\"500\"><input type=\"button\" ztype=\"button\" value=\"浏览任务内容\" class=\"input_submit_4\" /></a>";
		}
		return button;
	}

	private SecurityService securityService;
	private WorkFlowService workFlowService;

	@Override
	@Autowired
	public void setSecurityService(SecurityService securityService) {
		this.securityService = securityService;
	}

	@Autowired
	public void setWorkFlowService(WorkFlowService workFlowService) {
		this.workFlowService = workFlowService;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<String> getComments() {
		return comments;
	}

	public void setComments(List<String> comments) {
		this.comments = comments;
	}

	public ProcessInstance getPi() {
		return pi;
	}

	public void setPi(ProcessInstance pi) {
		this.pi = pi;
	}

	public String getButton() {
		return button;
	}

	public void setButton(String button) {
		this.button = button;
	}

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public boolean isCanExecute() {
		return canExecute;
	}

	public void setCanExecute(boolean canExecute) {
		this.canExecute = canExecute;
	}
}