USE [master]
GO
CREATE DATABASE [tjetms-bes] ON  PRIMARY 
( NAME = N'tjetms-bes', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\tjetms-bes.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'tjetms-bes_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL.1\MSSQL\DATA\tjetms-bes_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'tjetms-bes', @new_cmptlevel=90
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [tjetms-bes].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [tjetms-bes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [tjetms-bes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [tjetms-bes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [tjetms-bes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [tjetms-bes] SET ARITHABORT OFF 
GO
ALTER DATABASE [tjetms-bes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [tjetms-bes] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [tjetms-bes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [tjetms-bes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [tjetms-bes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [tjetms-bes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [tjetms-bes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [tjetms-bes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [tjetms-bes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [tjetms-bes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [tjetms-bes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [tjetms-bes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [tjetms-bes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [tjetms-bes] SET  READ_WRITE 
GO
ALTER DATABASE [tjetms-bes] SET RECOVERY FULL 
GO
ALTER DATABASE [tjetms-bes] SET  MULTI_USER 
GO
ALTER DATABASE [tjetms-bes] SET PAGE_VERIFY CHECKSUM  
GO
USE [tjetms-bes]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [tjetms-bes] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
