--清理数据--
--delete from JBPM_ID_MEMBERSHIP
--GO
--delete from JBPM_ID_USER
--GO
--delete from JBPM_ID_GROUP
--GO
--标识种子置0--
--DBCC CHECKIDENT (JBPM_ID_GROUP , RESEED , 0) 
--GO
--DBCC CHECKIDENT (JBPM_ID_USER , RESEED , 0)
--GO
--DBCC CHECKIDENT (JBPM_ID_MEMBERSHIP , RESEED , 0)
--GO
--初始化数据--
INSERT INTO JBPM_ID_GROUP VALUES('G','sales','organisation',NULL);
GO
INSERT INTO JBPM_ID_GROUP VALUES('G','admin','security-role',NULL);
GO
INSERT INTO JBPM_ID_GROUP VALUES('G','user','security-role',NULL);
GO
INSERT INTO JBPM_ID_GROUP VALUES('G','hr','organisation',NULL);
GO
INSERT INTO JBPM_ID_GROUP VALUES('G','manager','security-role',NULL);
GO
INSERT INTO JBPM_ID_USER VALUES('U','user','user@sample.domain','user');
GO
INSERT INTO JBPM_ID_USER VALUES('U','manager','manager@sample.domain','manager');
GO
INSERT INTO JBPM_ID_USER VALUES('U','admin','admin@sample.domain','admin');
GO
INSERT INTO JBPM_ID_USER VALUES('U','shipper','shipper@sample.domain','shipper');
GO
INSERT INTO JBPM_ID_USER VALUES('U','ROLE_WATCH','','');
GO
INSERT INTO JBPM_ID_USER VALUES('U','ROLE_DIRECTOR','','');
GO
INSERT INTO JBPM_ID_USER VALUES('U','ROLE_TEKOFFICER','','');
GO
INSERT INTO JBPM_ID_USER VALUES('U','ROLE_OFFICER','','');
GO
INSERT INTO JBPM_ID_USER VALUES('U','ROLE_GOVERNOR','','');
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,2,4);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,3,4);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,4,4);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,4,3);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,1,3);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,2,3);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,3,3);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,3,2);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,2,2);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,2,5);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,'boss',2,1);
GO
INSERT INTO JBPM_ID_MEMBERSHIP VALUES('M',NULL,NULL,1,1);
GO