ALTER TABLE TB_ETMS_ACCD_ABN_EQUIP DROP CONSTRAINT FKE8BCE83B96262CF0
GO
ALTER TABLE TB_ETMS_ACCD_ABN_EQUIP DROP CONSTRAINT FKE8BCE83B26650F9D
GO
ALTER TABLE TB_ETMS_ACCD_ABN_EQUIP DROP CONSTRAINT FKE8BCE83B96204410
GO
ALTER TABLE TB_ETMS_ACCD_ABN_OPERATION DROP CONSTRAINT FK166E57F26D138403
GO
ALTER TABLE TB_ETMS_ACCD_ABN_OPERATION DROP CONSTRAINT FK166E57F26AE10889
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL DROP CONSTRAINT FKC658C24BC75AF256
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL DROP CONSTRAINT FKC658C24B2349A917
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL DROP CONSTRAINT FKC658C24BA89E4F77
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL DROP CONSTRAINT FKC658C24BC75920DA
GO
ALTER TABLE TB_ETMS_ACCD_DUTY_TIME DROP CONSTRAINT FKC4B090F31850805A
GO
ALTER TABLE TB_ETMS_ACCD_DUTY_TIME DROP CONSTRAINT FKC4B090F343EAEFAB
GO
ALTER TABLE TB_ETMS_BASE_CAWAVE_PG_REF DROP CONSTRAINT FKFD45815EA684125D
GO
ALTER TABLE TB_ETMS_BASE_CAWAVE_PG_REF DROP CONSTRAINT FKFD45815E57D3AED7
GO
ALTER TABLE TB_ETMS_BASE_CHANNEL DROP CONSTRAINT FK38BD9B6E230E1F8D
GO
ALTER TABLE TB_ETMS_BASE_CHANNEL_EQUIP_REF DROP CONSTRAINT FK8A5F5C7326650F9D
GO
ALTER TABLE TB_ETMS_BASE_CHANNEL_EQUIP_REF DROP CONSTRAINT FK8A5F5C736FF90DFD
GO
ALTER TABLE TB_ETMS_BASE_DEPT DROP CONSTRAINT FKD3706FBAA246A48F
GO
ALTER TABLE TB_ETMS_BASE_DEPT DROP CONSTRAINT FKD3706FBA4C7A1C10
GO
ALTER TABLE TB_ETMS_BASE_DP_TRTP DROP CONSTRAINT FK7B3137B8A89E4F77
GO
ALTER TABLE TB_ETMS_BASE_DP_TRTP DROP CONSTRAINT FK7B3137B8923333B0
GO
ALTER TABLE TB_ETMS_BASE_EQUIP DROP CONSTRAINT FK9AB1255B923333B0
GO
ALTER TABLE TB_ETMS_BASE_EQUIP DROP CONSTRAINT FK9AB1255B1C7F4D6
GO
ALTER TABLE TB_ETMS_BASE_EQUIP DROP CONSTRAINT FK9AB1255BAA73B23
GO
ALTER TABLE TB_ETMS_BASE_EQUIP DROP CONSTRAINT FK9AB1255BDFAC522B
GO
ALTER TABLE TB_ETMS_BASE_EQUIP DROP CONSTRAINT FK9AB1255BD56C8077
GO
ALTER TABLE TB_ETMS_BASE_EQUIP DROP CONSTRAINT FK9AB1255B230E1F8D
GO
ALTER TABLE TB_ETMS_BASE_GROUP DROP CONSTRAINT FK9ACDB3AA923333B0
GO
ALTER TABLE TB_ETMS_BASE_GROUP DROP CONSTRAINT FK9ACDB3AAC5465A57
GO
ALTER TABLE TB_ETMS_BASE_OPERATION DROP CONSTRAINT FKBBF05127C47E18A
GO
ALTER TABLE TB_ETMS_BASE_OPERATION DROP CONSTRAINT FKBBF05124542CFD
GO
ALTER TABLE TB_ETMS_BASE_OPERATION DROP CONSTRAINT FKBBF0512A89E4F77
GO
ALTER TABLE TB_ETMS_BASE_OPERATION DROP CONSTRAINT FKBBF0512E220C023
GO
ALTER TABLE TB_ETMS_BASE_OPERATION DROP CONSTRAINT FKBBF0512A684125D
GO
ALTER TABLE TB_ETMS_BASE_OPERATION DROP CONSTRAINT FKBBF051294C3E213
GO
ALTER TABLE TB_ETMS_BASE_OPERATION DROP CONSTRAINT FKBBF0512E2213482
GO
ALTER TABLE TB_ETMS_BASE_PERSON DROP CONSTRAINT FKCD8E838A923333B0
GO
ALTER TABLE TB_ETMS_BASE_PERSON DROP CONSTRAINT FKCD8E838A8CB7DCFD
GO
ALTER TABLE TB_ETMS_BASE_PERSON DROP CONSTRAINT FKCD8E838A2196393D
GO
ALTER TABLE TB_ETMS_BASE_PROGRAM DROP CONSTRAINT FKFA413CEFEFCA59F7
GO
ALTER TABLE TB_ETMS_BASE_SCHEDULE DROP CONSTRAINT FK5FF8418C6D138403
GO
ALTER TABLE TB_ETMS_BASE_SCHEDULE DROP CONSTRAINT FK5FF8418C6FF90DFD
GO
ALTER TABLE TB_ETMS_BASE_STATION DROP CONSTRAINT FK9B9E1F9FBD949870
GO
ALTER TABLE TB_ETMS_BASE_STATION DROP CONSTRAINT FK9B9E1F9FA94BAFF7
GO
ALTER TABLE TB_ETMS_BASE_STATION DROP CONSTRAINT FK9B9E1F9FFA371FAF
GO
ALTER TABLE TB_ETMS_BASE_TACHE DROP CONSTRAINT FK9B7CFC3EA89E4F77
GO
ALTER TABLE TB_ETMS_BASE_TECHSYSTEM DROP CONSTRAINT FK10E1B1FAA89E4F77
GO
ALTER TABLE TB_ETMS_BASE_TRANSFER DROP CONSTRAINT FKD5EA66E0705B6B4D
GO
ALTER TABLE TB_ETMS_DUTY_CHECK DROP CONSTRAINT FKA259FE786EC89BA5
GO
ALTER TABLE TB_ETMS_DUTY_DUTY DROP CONSTRAINT FK709833661BDE3B0E
GO
ALTER TABLE TB_ETMS_DUTY_DUTY DROP CONSTRAINT FK709833662196393D
GO
ALTER TABLE TB_ETMS_DUTY_PROMPT DROP CONSTRAINT FKBFA66DF46EC89BA5
GO
ALTER TABLE TB_ETMS_DUTY_RECORD DROP CONSTRAINT FKC25380E12780E7F9
GO
ALTER TABLE TB_ETMS_DUTY_RECORD DROP CONSTRAINT FKC25380E1FA966D54
GO
ALTER TABLE TB_ETMS_DUTY_RECORD DROP CONSTRAINT FKC25380E1D31EBA28
GO
ALTER TABLE TB_ETMS_DUTY_RECORD DROP CONSTRAINT FKC25380E16AE10889
GO
ALTER TABLE TB_ETMS_DUTY_RECORD DROP CONSTRAINT FKC25380E16EC89BA5
GO
ALTER TABLE TB_ETMS_DUTY_RULE_ITEM DROP CONSTRAINT FK3B757BE6BD230575
GO
ALTER TABLE TB_ETMS_DUTY_RULE_ITEM DROP CONSTRAINT FK3B757BE62196393D
GO
ALTER TABLE TB_ETMS_DUTY_SCHEDULE DROP CONSTRAINT FK8180C327A3F981CF
GO
ALTER TABLE TB_ETMS_DUTY_SCHEDULE_RULE DROP CONSTRAINT FK777E6D14923333B0
GO
ALTER TABLE TB_ETMS_DUTY_STAFF_ON_DUTY DROP CONSTRAINT FKC589EC47E014A937
GO
ALTER TABLE TB_ETMS_DUTY_STAFF_ON_DUTY DROP CONSTRAINT FKC589EC47E01934ED
GO
ALTER TABLE TB_ETMS_DUTY_WARNING DROP CONSTRAINT FK8A9B2D0C6D138403
GO
ALTER TABLE TB_ETMS_DUTY_WARNING DROP CONSTRAINT FK8A9B2D0C48981CAF
GO
ALTER TABLE TB_ETMS_REPAIR_CARD DROP CONSTRAINT FKA4B9D389A5F25A71
GO
ALTER TABLE TB_ETMS_REPAIR_CARD DROP CONSTRAINT FKA4B9D389C3E9C9
GO
ALTER TABLE TB_ETMS_REPAIR_CYCLE DROP CONSTRAINT FKF28B4F8DE926BB57
GO
ALTER TABLE TB_ETMS_REPAIR_CYCLE_CELL DROP CONSTRAINT FKB132A2D4D1F6726B
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD DROP CONSTRAINT FK775D8A8A2196393D
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_ITEM DROP CONSTRAINT FK871AFA8D65ED329
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_ITEM DROP CONSTRAINT FK871AFA81D999FC9
GO
ALTER TABLE TB_ETMS_REPT_BROAD_BY_TIME DROP CONSTRAINT FKE6E43D496D138403
GO
ALTER TABLE TB_SEC_DEPT_PER DROP CONSTRAINT FK9A3FB282923333B0
GO
ALTER TABLE TB_SEC_DEPT_PER DROP CONSTRAINT FK9A3FB2822AC41FC4
GO
ALTER TABLE TB_SEC_PRI_ASS DROP CONSTRAINT FK95876AAA2AC41FC4
GO
ALTER TABLE TB_SEC_PRI_ASS DROP CONSTRAINT FK95876AAA41BD19CD
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_EQUIP DROP CONSTRAINT FK58AC63B26650F9D
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_EQUIP DROP CONSTRAINT FK58AC63BB614230C
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_PERSON DROP CONSTRAINT FKBDE8FEAAAB10E617
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_PERSON DROP CONSTRAINT FKBDE8FEAAB614230C
GO
DROP TABLE TB_ETMS_ACCD_ABN_EQUIP
GO
DROP TABLE TB_ETMS_ACCD_ABN_OPERATION
GO
DROP TABLE TB_ETMS_ACCD_ABNORMAL
GO
DROP TABLE TB_ETMS_ACCD_DUTY_TIME
GO
DROP TABLE TB_ETMS_BASE_CAWAVE
GO
DROP TABLE TB_ETMS_BASE_CAWAVE_PG_REF
GO
DROP TABLE TB_ETMS_BASE_CHANNEL
GO
DROP TABLE TB_ETMS_BASE_CHANNEL_EQUIP_REF
GO
DROP TABLE TB_ETMS_BASE_DEPT
GO
DROP TABLE TB_ETMS_BASE_DP_TRTP
GO
DROP TABLE TB_ETMS_BASE_EQUIP
GO
DROP TABLE TB_ETMS_BASE_GROUP
GO
DROP TABLE TB_ETMS_BASE_OPERATION
GO
DROP TABLE TB_ETMS_BASE_PARA_DTL
GO
DROP TABLE TB_ETMS_BASE_PERSON
GO
DROP TABLE TB_ETMS_BASE_POST
GO
DROP TABLE TB_ETMS_BASE_PROGRAM
GO
DROP TABLE TB_ETMS_BASE_ROUTE
GO
DROP TABLE TB_ETMS_BASE_SATELLITE
GO
DROP TABLE TB_ETMS_BASE_SCHEDULE
GO
DROP TABLE TB_ETMS_BASE_STATION
GO
DROP TABLE TB_ETMS_BASE_TACHE
GO
DROP TABLE TB_ETMS_BASE_TECHSYSTEM
GO
DROP TABLE TB_ETMS_BASE_TRANSFER
GO
DROP TABLE TB_ETMS_DUTY_CHECK
GO
DROP TABLE TB_ETMS_DUTY_DUTY
GO
DROP TABLE TB_ETMS_DUTY_PATROL_TIME
GO
DROP TABLE TB_ETMS_DUTY_PROMPT
GO
DROP TABLE TB_ETMS_DUTY_RECORD
GO
DROP TABLE TB_ETMS_DUTY_RULE_ITEM
GO
DROP TABLE TB_ETMS_DUTY_SCHEDULE
GO
DROP TABLE TB_ETMS_DUTY_SCHEDULE_RULE
GO
DROP TABLE TB_ETMS_DUTY_STAFF_ON_DUTY
GO
DROP TABLE TB_ETMS_DUTY_WARNING
GO
DROP TABLE TB_ETMS_REPAIR_CARD
GO
DROP TABLE TB_ETMS_REPAIR_CYCLE
GO
DROP TABLE TB_ETMS_REPAIR_CYCLE_CELL
GO
DROP TABLE TB_ETMS_REPAIR_PERIOD
GO
DROP TABLE TB_ETMS_REPAIR_RECORD
GO
DROP TABLE TB_ETMS_REPAIR_RECORD_ITEM
GO
DROP TABLE TB_ETMS_REPT_BROAD_BY_TIME
GO
DROP TABLE TB_SEC_DEPT_PER
GO
DROP TABLE TB_SEC_PRI_ASS
GO
DROP TABLE TB_SEC_ROLE
GO
DROP TABLE TB_ETMS_REPAIR_RECORD_EQUIP
GO
DROP TABLE TB_ETMS_REPAIR_RECORD_PERSON
GO

CREATE TABLE TB_ETMS_ACCD_ABN_EQUIP (ID NUMERIC(19,0) IDENTITY NOT NULL, END_TIME DATETIME NOT NULL, SORTBY INT NOT NULL, START_TIME DATETIME NOT NULL, ABN_B_ID NUMERIC(19,0) NULL, ABN_O_ID NUMERIC(19,0) NOT NULL, EQUIP_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_ACCD_ABN_OPERATION (ACCD_FLAG VARCHAR(1) NOT NULL, ID NUMERIC(19,0) IDENTITY NOT NULL, END_TIME DATETIME NOT NULL, SORTBY INT NOT NULL, START_TIME DATETIME NOT NULL, ABN_ID NUMERIC(19,0) NOT NULL, OP_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_ACCD_ABNORMAL (ABNORMAL_TYPE VARCHAR(1) NOT NULL, ID NUMERIC(19,0) IDENTITY NOT NULL, ACCD_CODE VARCHAR(20) NULL, PREV_WAY VARCHAR(2048) NULL, ABN_DESC VARCHAR(512) NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, END_TIME DATETIME NOT NULL, PROC_CODE VARCHAR(4) NULL, PROCESS_STEP VARCHAR(512) NOT NULL, REASON VARCHAR(512) NOT NULL, START_TIME DATETIME NOT NULL, UPD_DATE DATETIME NOT NULL, ABN_TYPE NUMERIC(19,0) NOT NULL, TRANS_TYPE NUMERIC(19,0) NOT NULL, EQUIP_B_ID NUMERIC(19,0) NULL, EQUIP_F_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_ACCD_DUTY_TIME (ID NUMERIC(19,0) IDENTITY NOT NULL, DUTY_TIME INT NOT NULL, SORTBY INT NOT NULL, ABN_OP_ID NUMERIC(19,0) NOT NULL, DUTY_CODE NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_CAWAVE (ID NUMERIC(19,0) IDENTITY NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, CAWAVE_NAME VARCHAR(64) NOT NULL, UPD_DATE DATETIME NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_CAWAVE_PG_REF (ID NUMERIC(19,0) IDENTITY NOT NULL, END_DATE DATETIME NULL, START_DATE DATETIME NOT NULL, CAWAVE_ID NUMERIC(19,0) NOT NULL, PROGRAM_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_CHANNEL (ID NUMERIC(19,0) IDENTITY NOT NULL, CHANNEL_NAME VARCHAR(20) NOT NULL, SYSTEM_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_CHANNEL_EQUIP_REF (EQUIP_ID NUMERIC(19,0) NOT NULL, CHANNEL_ID NUMERIC(19,0) NOT NULL)
GO
CREATE TABLE TB_ETMS_BASE_DEPT (ID NUMERIC(19,0) IDENTITY NOT NULL, DEPT_CODE VARCHAR(4) NOT NULL UNIQUE, DEPT_NAME VARCHAR(100) NOT NULL, DEPT_TYPE NUMERIC(19,0) NOT NULL, ST_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_DP_TRTP (TRANS_TYPE NUMERIC(19,0) NOT NULL, DP_ID NUMERIC(19,0) NOT NULL)
GO
CREATE TABLE TB_ETMS_BASE_EQUIP (IS_EQUIP VARCHAR(1) NOT NULL, ID NUMERIC(19,0) IDENTITY NOT NULL, EQUIP_CODE VARCHAR(24) NULL, DEAL_TIME DATETIME NULL, DESIGN_LIFE INT NULL, EMP_NAME VARCHAR(20) NOT NULL, EQUIP_STATUS VARCHAR(4) NULL, EQUIP_FLAG TINYINT NOT NULL, MA_NAME VARCHAR(20) NULL, EQUIP_MODEL VARCHAR(30) NULL, EQUIP_NAME VARCHAR(50) NOT NULL UNIQUE, POSITION VARCHAR(4) NULL, PRODUCT_ADDR VARCHAR(20) NULL, RUN_TIME DATETIME NULL, EQUIP_SN VARCHAR(20) NULL, UPD_DATE DATETIME NOT NULL, DP_ID NUMERIC(19,0) NULL, EQUIP_TYPE NUMERIC(19,0) NOT NULL, ORI_EQUIP_ID NUMERIC(19,0) NULL, PA_EQUIP_ID NUMERIC(19,0) NULL, TA_ID NUMERIC(19,0) NULL, SYSTEM_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_GROUP (ID NUMERIC(19,0) IDENTITY NOT NULL, GROUP_NAME VARCHAR(64) NOT NULL, DP_ID NUMERIC(19,0) NOT NULL, GROUP_TYPE NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_OPERATION (OPERATION_TYPE VARCHAR(1) NOT NULL, ID NUMERIC(19,0) IDENTITY NOT NULL, CAWAVE_FRQ DOUBLE PRECISION NOT NULL, CHANNEL_RATE DOUBLE PRECISION NULL, EMP_NAME VARCHAR(20) NOT NULL, END_DATE DATETIME NULL, OP_NAME VARCHAR(64) NULL UNIQUE, RMKS VARCHAR(128) NULL, SYMBLE_RATE DOUBLE PRECISION NOT NULL, START_DATE DATETIME NOT NULL, UPD_DATE DATETIME NOT NULL, TRANS_TYPE NUMERIC(19,0) NOT NULL, TRANS_MODE NUMERIC(19,0) NOT NULL, PROGRAM_ID NUMERIC(19,0) NULL, CAWAVE_S_ID NUMERIC(19,0) NULL, SK_ID NUMERIC(19,0) NULL, CAWAVE_T_ID NUMERIC(19,0) NULL, ROUTE_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_PARA_DTL (PARA_TYPE VARCHAR(4) NOT NULL, ID NUMERIC(19,0) IDENTITY NOT NULL, CODE_DESC VARCHAR(40) NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, PARA_CODE VARCHAR(255) NULL, SORTBY VARCHAR(4) NULL, UPD_DATE DATETIME NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_PERSON (ID NUMERIC(19,0) IDENTITY NOT NULL, AD_ID VARCHAR(50) NULL, EMP_CODE VARCHAR(10) NULL, DORM VARCHAR(100) NULL, EMAIL VARCHAR(100) NULL, IS_ENABLE VARCHAR(1) NOT NULL, IDTY_CARD VARCHAR(18) NULL, LOGIN_NAME VARCHAR(60) NULL, LOGIN_PASSWORD VARCHAR(60) NULL, MOBILE VARCHAR(20) NULL, EMP_NAME VARCHAR(20) NULL, OFFICE_PASSWORD VARCHAR(40) NULL, OFFICE_TEL VARCHAR(40) NULL, SEX TINYINT NULL, DP_ID NUMERIC(19,0) NULL, GROUP_ID NUMERIC(19,0) NULL, POST NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_POST (ID NUMERIC(19,0) IDENTITY NOT NULL, POST_NAME VARCHAR(20) NOT NULL, POST VARCHAR(4) NOT NULL, SORT INT NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_PROGRAM (ID NUMERIC(19,0) IDENTITY NOT NULL, PROGRAM_CODE VARCHAR(20) NOT NULL UNIQUE, EMP_NAME VARCHAR(20) NOT NULL, PROGRAM_NAME VARCHAR(64) NOT NULL, UPD_DATE DATETIME NOT NULL, PROGRAM_TYPE NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_ROUTE (ID NUMERIC(19,0) IDENTITY NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, FROM_PL VARCHAR(20) NOT NULL, TO_PL VARCHAR(20) NOT NULL, UPD_DATE DATETIME NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_SATELLITE (ID NUMERIC(19,0) IDENTITY NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, STL_NAME VARCHAR(20) NOT NULL UNIQUE, STL_ORBIT VARCHAR(64) NULL, UPD_DATE DATETIME NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_SCHEDULE (ID NUMERIC(19,0) IDENTITY NOT NULL, END_DATE DATETIME NOT NULL, START_DATE DATETIME NOT NULL, CHANNEL_ID NUMERIC(19,0) NOT NULL, OP_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_STATION (ID NUMERIC(19,0) IDENTITY NOT NULL, S_CODE VARCHAR(20) NOT NULL, ACREAGE INT NOT NULL, STATION_ADDR VARCHAR(100) NULL, ALTITUDE INT NOT NULL, STATION_BREV VARCHAR(1024) NULL, BUILD_DATE DATETIME NOT NULL, STATION_CODE VARCHAR(2) NOT NULL UNIQUE, GEO_INFOR VARCHAR(1024) NULL, LATITUDE VARCHAR(20) NULL, LOC VARCHAR(3) NULL, LONGITUDE VARCHAR(20) NULL, STATION_NAME VARCHAR(100) NOT NULL, REGION_CODE VARCHAR(6) NOT NULL, RMKS VARCHAR(200) NULL, START_DATE DATETIME NOT NULL, DISTRICT_TYPE NUMERIC(19,0) NOT NULL, STATION_TYPE NUMERIC(19,0) NOT NULL, TRANSMIT_UNIT_TYPE NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_TACHE (ID NUMERIC(19,0) IDENTITY NOT NULL, TA_NAME VARCHAR(20) NOT NULL, TRANS_TYPE NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_TECHSYSTEM (ID NUMERIC(19,0) IDENTITY NOT NULL, TECH_CODE VARCHAR(4) NOT NULL UNIQUE, TECH_NAME VARCHAR(60) NULL, TRANS_TYPE NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_BASE_TRANSFER (ID NUMERIC(19,0) IDENTITY NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, SK_NAME VARCHAR(20) NOT NULL, UPD_DATE DATETIME NOT NULL, STL_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_CHECK (ID NUMERIC(19,0) IDENTITY NOT NULL, CONTENT VARCHAR(1024) NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, START_TIME DATETIME NOT NULL, DU_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_DUTY (ID NUMERIC(19,0) IDENTITY NOT NULL, CONFIRM TINYINT NULL, DAY_PART_COUNT INT NOT NULL, EMP_NAME VARCHAR(20) NULL, END_TIME DATETIME NOT NULL, FIRST TINYINT NULL, LAST TINYINT NULL, OFF_DUTY_RECORD VARCHAR(1024) NULL, ON_DUTY_RECORD VARCHAR(1024) NULL, SCH_NAME VARCHAR(255) NULL, START_TIME DATETIME NOT NULL, TEMPERATURE VARCHAR(10) NULL, UPD_DATE DATETIME NULL, WEATHER VARCHAR(100) NULL, WEEK VARCHAR(255) NULL, GROUP_ID NUMERIC(19,0) NOT NULL, PRE_DUTY NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_PATROL_TIME (ID NUMERIC(19,0) IDENTITY NOT NULL, CONTENT VARCHAR(512) NULL, DDATE DATETIME NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, END_TIME DATETIME NOT NULL, START_TIME DATETIME NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_PROMPT (ID NUMERIC(19,0) IDENTITY NOT NULL, CONTENT VARCHAR(512) NULL, DDATE DATETIME NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, END_TIME DATETIME NOT NULL, START_TIME DATETIME NOT NULL, DU_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_RECORD (REC_TYPE VARCHAR(1) NOT NULL, ID NUMERIC(19,0) IDENTITY NOT NULL, COMMENT VARCHAR(1024) NULL, CONTENT VARCHAR(1024) NULL, MESSAGE VARCHAR(1024) NULL, START_TIME DATETIME NOT NULL, DU_ID NUMERIC(19,0) NULL, ABN_ID NUMERIC(19,0) NULL, BROAD_ID NUMERIC(19,0) NULL, PA_ID NUMERIC(19,0) NULL, WARN_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_RULE_ITEM (ID NUMERIC(19,0) IDENTITY NOT NULL, PERIOD_DAY_NUM INT NOT NULL, SCH_ID NUMERIC(19,0) NOT NULL, GROUP_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_SCHEDULE (ID NUMERIC(19,0) IDENTITY NOT NULL, END_TIME DATETIME NOT NULL, SCH_NAME VARCHAR(20) NOT NULL, SCH_ORDER INT NOT NULL, START_TIME DATETIME NOT NULL, RU_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_SCHEDULE_RULE (ID NUMERIC(19,0) IDENTITY NOT NULL, DAY_PART_COUNT INT NOT NULL, RMKS VARCHAR(50) NULL, RULE_NAME VARCHAR(50) NOT NULL, DP_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_STAFF_ON_DUTY (MONITER VARCHAR(1) NOT NULL, ID NUMERIC(19,0) IDENTITY NOT NULL, END_TIME DATETIME NOT NULL, EMP_NAME VARCHAR(20) NOT NULL, START_TIME DATETIME NOT NULL, DU_M_ID NUMERIC(19,0) NULL, DU_W_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_DUTY_WARNING (ID NUMERIC(19,0) IDENTITY NOT NULL, ANALYSIS VARCHAR(512) NULL, PROCESS VARCHAR(256) NULL, WARN_TIME DATETIME NULL, OP_ID NUMERIC(19,0) NULL, WARN_TYPE NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPAIR_CARD (ID NUMERIC(19,0) IDENTITY NOT NULL, ACTIVE VARCHAR(1) NOT NULL, ATTENTION VARCHAR(600) NULL, EQUIP_TYPE VARCHAR(3) NULL, MEASURE VARCHAR(600) NULL, METHODS VARCHAR(4000) NULL, NAME VARCHAR(100) NOT NULL, OTHER VARCHAR(600) NULL, PROCESS_TIME DOUBLE PRECISION NULL, REMARK VARCHAR(600) NULL, SHUTDOWN_TIME DOUBLE PRECISION NULL, TECHNICAL_STANDARDS VARCHAR(1024) NULL, TOOLS VARCHAR(600) NULL, CELL_ID NUMERIC(19,0) NOT NULL, PERIOD_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPAIR_CYCLE (ID NUMERIC(19,0) IDENTITY NOT NULL, ACTIVE VARCHAR(1) NOT NULL, NAME VARCHAR(100) NOT NULL, DEPT_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPAIR_CYCLE_CELL (ID NUMERIC(19,0) IDENTITY NOT NULL, NAME VARCHAR(100) NOT NULL, CYCLE_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPAIR_PERIOD (ID NUMERIC(19,0) IDENTITY NOT NULL, END_DAY DATETIME NULL, NAME VARCHAR(100) NOT NULL, PREVIOUS_VALUE INT NOT NULL, START_DAY DATETIME NULL, TYPE VARCHAR(1) NOT NULL, VALUE INT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPAIR_RECORD (ID NUMERIC(19,0) IDENTITY NOT NULL, CHECKER VARCHAR(40) NULL, DDATE DATETIME NOT NULL, DEPTMENT VARCHAR(100) NULL, EXAMINE_PERSONS VARCHAR(100) NULL, EXAMINE_RECORD VARCHAR(1024) NULL, MEASURE VARCHAR(512) NULL, PERSON_NAME VARCHAR(20) NOT NULL, PRINCIPAL VARCHAR(40) NULL, SECURITY VARCHAR(40) NULL, TEST VARCHAR(512) NULL, TIME_LENGTH INT NOT NULL, UPD_DATE DATETIME NOT NULL, GROUP_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPAIR_RECORD_ITEM (ID NUMERIC(19,0) IDENTITY NOT NULL, CONTENT VARCHAR(512) NULL, CYCLE_NAME VARCHAR(100) NULL, TYPE VARCHAR(1) NULL, CARD_ID NUMERIC(19,0) NULL, RECORD_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPT_BROAD_BY_TIME (ID NUMERIC(19,0) IDENTITY NOT NULL, AUTO_FLAG TINYINT NULL, BROAD_BY_FLAG TINYINT NULL, BROAD_REASON VARCHAR(1024) NULL, BROAD_RESULT VARCHAR(512) NULL, EMP_NAME VARCHAR(20) NULL, END_TIME DATETIME NULL, NOTIFY_PERSON VARCHAR(64) NULL, START_TIME DATETIME NULL, STATION VARCHAR(20) NULL, OP_ID NUMERIC(19,0) NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_SEC_DEPT_PER (ID NUMERIC(19,0) IDENTITY NOT NULL, FUN_MODULE VARCHAR(50) NULL, DP_ID NUMERIC(19,0) NOT NULL, EMP_ID NUMERIC(19,0) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_SEC_PRI_ASS (EMP_ID NUMERIC(19,0) NOT NULL, ROLE_ID NUMERIC(19,0) NOT NULL)
GO
CREATE TABLE TB_SEC_ROLE (ID NUMERIC(19,0) IDENTITY NOT NULL, ROLE_DESC VARCHAR(50) NOT NULL, ROLE_NAME VARCHAR(255) NOT NULL, PRIMARY KEY (ID))
GO
CREATE TABLE TB_ETMS_REPAIR_RECORD_EQUIP (RECORD_ITEM_ID NUMERIC(19,0) NOT NULL, EQUIP_ID NUMERIC(19,0) NOT NULL)
GO
CREATE TABLE TB_ETMS_REPAIR_RECORD_PERSON (RECORD_ITEM_ID NUMERIC(19,0) NOT NULL, PERSON_ID NUMERIC(19,0) NOT NULL)
GO


ALTER TABLE TB_ETMS_ACCD_ABN_EQUIP ADD CONSTRAINT FKE8BCE83B96262CF0 FOREIGN KEY (ABN_O_ID) REFERENCES TB_ETMS_ACCD_ABNORMAL
GO
ALTER TABLE TB_ETMS_ACCD_ABN_EQUIP ADD CONSTRAINT FKE8BCE83B26650F9D FOREIGN KEY (EQUIP_ID) REFERENCES TB_ETMS_BASE_EQUIP
GO
ALTER TABLE TB_ETMS_ACCD_ABN_EQUIP ADD CONSTRAINT FKE8BCE83B96204410 FOREIGN KEY (ABN_B_ID) REFERENCES TB_ETMS_ACCD_ABNORMAL
GO
ALTER TABLE TB_ETMS_ACCD_ABN_OPERATION ADD CONSTRAINT FK166E57F26D138403 FOREIGN KEY (OP_ID) REFERENCES TB_ETMS_BASE_OPERATION
GO
ALTER TABLE TB_ETMS_ACCD_ABN_OPERATION ADD CONSTRAINT FK166E57F26AE10889 FOREIGN KEY (ABN_ID) REFERENCES TB_ETMS_ACCD_ABNORMAL
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL ADD CONSTRAINT FKC658C24BC75AF256 FOREIGN KEY (EQUIP_F_ID) REFERENCES TB_ETMS_BASE_EQUIP
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL ADD CONSTRAINT FKC658C24B2349A917 FOREIGN KEY (ABN_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL ADD CONSTRAINT FKC658C24BA89E4F77 FOREIGN KEY (TRANS_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_ACCD_ABNORMAL ADD CONSTRAINT FKC658C24BC75920DA FOREIGN KEY (EQUIP_B_ID) REFERENCES TB_ETMS_BASE_EQUIP
GO
ALTER TABLE TB_ETMS_ACCD_DUTY_TIME ADD CONSTRAINT FKC4B090F31850805A FOREIGN KEY (ABN_OP_ID) REFERENCES TB_ETMS_ACCD_ABN_OPERATION
GO
ALTER TABLE TB_ETMS_ACCD_DUTY_TIME ADD CONSTRAINT FKC4B090F343EAEFAB FOREIGN KEY (DUTY_CODE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_CAWAVE_PG_REF ADD CONSTRAINT FKFD45815EA684125D FOREIGN KEY (PROGRAM_ID) REFERENCES TB_ETMS_BASE_PROGRAM
GO
ALTER TABLE TB_ETMS_BASE_CAWAVE_PG_REF ADD CONSTRAINT FKFD45815E57D3AED7 FOREIGN KEY (CAWAVE_ID) REFERENCES TB_ETMS_BASE_CAWAVE
GO
ALTER TABLE TB_ETMS_BASE_CHANNEL ADD CONSTRAINT FK38BD9B6E230E1F8D FOREIGN KEY (SYSTEM_ID) REFERENCES TB_ETMS_BASE_TECHSYSTEM
GO
ALTER TABLE TB_ETMS_BASE_CHANNEL_EQUIP_REF ADD CONSTRAINT FK8A5F5C7326650F9D FOREIGN KEY (EQUIP_ID) REFERENCES TB_ETMS_BASE_EQUIP
GO
ALTER TABLE TB_ETMS_BASE_CHANNEL_EQUIP_REF ADD CONSTRAINT FK8A5F5C736FF90DFD FOREIGN KEY (CHANNEL_ID) REFERENCES TB_ETMS_BASE_CHANNEL
GO
ALTER TABLE TB_ETMS_BASE_DEPT ADD CONSTRAINT FKD3706FBAA246A48F FOREIGN KEY (DEPT_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_DEPT ADD CONSTRAINT FKD3706FBA4C7A1C10 FOREIGN KEY (ST_ID) REFERENCES TB_ETMS_BASE_STATION
GO
ALTER TABLE TB_ETMS_BASE_DP_TRTP ADD CONSTRAINT FK7B3137B8A89E4F77 FOREIGN KEY (TRANS_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_DP_TRTP ADD CONSTRAINT FK7B3137B8923333B0 FOREIGN KEY (DP_ID) REFERENCES TB_ETMS_BASE_DEPT
GO
ALTER TABLE TB_ETMS_BASE_EQUIP ADD CONSTRAINT FK9AB1255B923333B0 FOREIGN KEY (DP_ID) REFERENCES TB_ETMS_BASE_DEPT
GO
ALTER TABLE TB_ETMS_BASE_EQUIP ADD CONSTRAINT FK9AB1255B1C7F4D6 FOREIGN KEY (ORI_EQUIP_ID) REFERENCES TB_ETMS_BASE_EQUIP
GO
ALTER TABLE TB_ETMS_BASE_EQUIP ADD CONSTRAINT FK9AB1255BAA73B23 FOREIGN KEY (TA_ID) REFERENCES TB_ETMS_BASE_TACHE
GO
ALTER TABLE TB_ETMS_BASE_EQUIP ADD CONSTRAINT FK9AB1255BDFAC522B FOREIGN KEY (PA_EQUIP_ID) REFERENCES TB_ETMS_BASE_EQUIP
GO
ALTER TABLE TB_ETMS_BASE_EQUIP ADD CONSTRAINT FK9AB1255BD56C8077 FOREIGN KEY (EQUIP_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_EQUIP ADD CONSTRAINT FK9AB1255B230E1F8D FOREIGN KEY (SYSTEM_ID) REFERENCES TB_ETMS_BASE_TECHSYSTEM
GO
ALTER TABLE TB_ETMS_BASE_GROUP ADD CONSTRAINT FK9ACDB3AA923333B0 FOREIGN KEY (DP_ID) REFERENCES TB_ETMS_BASE_DEPT
GO
ALTER TABLE TB_ETMS_BASE_GROUP ADD CONSTRAINT FK9ACDB3AAC5465A57 FOREIGN KEY (GROUP_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_OPERATION ADD CONSTRAINT FKBBF05127C47E18A FOREIGN KEY (SK_ID) REFERENCES TB_ETMS_BASE_TRANSFER
GO
ALTER TABLE TB_ETMS_BASE_OPERATION ADD CONSTRAINT FKBBF05124542CFD FOREIGN KEY (ROUTE_ID) REFERENCES TB_ETMS_BASE_ROUTE
GO
ALTER TABLE TB_ETMS_BASE_OPERATION ADD CONSTRAINT FKBBF0512A89E4F77 FOREIGN KEY (TRANS_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_OPERATION ADD CONSTRAINT FKBBF0512E220C023 FOREIGN KEY (CAWAVE_S_ID) REFERENCES TB_ETMS_BASE_CAWAVE
GO
ALTER TABLE TB_ETMS_BASE_OPERATION ADD CONSTRAINT FKBBF0512A684125D FOREIGN KEY (PROGRAM_ID) REFERENCES TB_ETMS_BASE_PROGRAM
GO
ALTER TABLE TB_ETMS_BASE_OPERATION ADD CONSTRAINT FKBBF051294C3E213 FOREIGN KEY (TRANS_MODE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_OPERATION ADD CONSTRAINT FKBBF0512E2213482 FOREIGN KEY (CAWAVE_T_ID) REFERENCES TB_ETMS_BASE_CAWAVE
GO
ALTER TABLE TB_ETMS_BASE_PERSON ADD CONSTRAINT FKCD8E838A923333B0 FOREIGN KEY (DP_ID) REFERENCES TB_ETMS_BASE_DEPT
GO
ALTER TABLE TB_ETMS_BASE_PERSON ADD CONSTRAINT FKCD8E838A8CB7DCFD FOREIGN KEY (POST) REFERENCES TB_ETMS_BASE_POST
GO
ALTER TABLE TB_ETMS_BASE_PERSON ADD CONSTRAINT FKCD8E838A2196393D FOREIGN KEY (GROUP_ID) REFERENCES TB_ETMS_BASE_GROUP
GO
ALTER TABLE TB_ETMS_BASE_PROGRAM ADD CONSTRAINT FKFA413CEFEFCA59F7 FOREIGN KEY (PROGRAM_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_SCHEDULE ADD CONSTRAINT FK5FF8418C6D138403 FOREIGN KEY (OP_ID) REFERENCES TB_ETMS_BASE_OPERATION
GO
ALTER TABLE TB_ETMS_BASE_SCHEDULE ADD CONSTRAINT FK5FF8418C6FF90DFD FOREIGN KEY (CHANNEL_ID) REFERENCES TB_ETMS_BASE_CHANNEL
GO
ALTER TABLE TB_ETMS_BASE_STATION ADD CONSTRAINT FK9B9E1F9FBD949870 FOREIGN KEY (TRANSMIT_UNIT_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_STATION ADD CONSTRAINT FK9B9E1F9FA94BAFF7 FOREIGN KEY (STATION_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_STATION ADD CONSTRAINT FK9B9E1F9FFA371FAF FOREIGN KEY (DISTRICT_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_TACHE ADD CONSTRAINT FK9B7CFC3EA89E4F77 FOREIGN KEY (TRANS_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_TECHSYSTEM ADD CONSTRAINT FK10E1B1FAA89E4F77 FOREIGN KEY (TRANS_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_BASE_TRANSFER ADD CONSTRAINT FKD5EA66E0705B6B4D FOREIGN KEY (STL_ID) REFERENCES TB_ETMS_BASE_SATELLITE
GO
ALTER TABLE TB_ETMS_DUTY_CHECK ADD CONSTRAINT FKA259FE786EC89BA5 FOREIGN KEY (DU_ID) REFERENCES TB_ETMS_DUTY_DUTY
GO
ALTER TABLE TB_ETMS_DUTY_DUTY ADD CONSTRAINT FK709833661BDE3B0E FOREIGN KEY (PRE_DUTY) REFERENCES TB_ETMS_DUTY_DUTY
GO
ALTER TABLE TB_ETMS_DUTY_DUTY ADD CONSTRAINT FK709833662196393D FOREIGN KEY (GROUP_ID) REFERENCES TB_ETMS_BASE_GROUP
GO
ALTER TABLE TB_ETMS_DUTY_PROMPT ADD CONSTRAINT FKBFA66DF46EC89BA5 FOREIGN KEY (DU_ID) REFERENCES TB_ETMS_DUTY_DUTY
GO
ALTER TABLE TB_ETMS_DUTY_RECORD ADD CONSTRAINT FKC25380E12780E7F9 FOREIGN KEY (BROAD_ID) REFERENCES TB_ETMS_REPT_BROAD_BY_TIME
GO
ALTER TABLE TB_ETMS_DUTY_RECORD ADD CONSTRAINT FKC25380E1FA966D54 FOREIGN KEY (WARN_ID) REFERENCES TB_ETMS_DUTY_WARNING
GO
ALTER TABLE TB_ETMS_DUTY_RECORD ADD CONSTRAINT FKC25380E1D31EBA28 FOREIGN KEY (PA_ID) REFERENCES TB_ETMS_DUTY_PATROL_TIME
GO
ALTER TABLE TB_ETMS_DUTY_RECORD ADD CONSTRAINT FKC25380E16AE10889 FOREIGN KEY (ABN_ID) REFERENCES TB_ETMS_ACCD_ABNORMAL
GO
ALTER TABLE TB_ETMS_DUTY_RECORD ADD CONSTRAINT FKC25380E16EC89BA5 FOREIGN KEY (DU_ID) REFERENCES TB_ETMS_DUTY_DUTY
GO
ALTER TABLE TB_ETMS_DUTY_RULE_ITEM ADD CONSTRAINT FK3B757BE6BD230575 FOREIGN KEY (SCH_ID) REFERENCES TB_ETMS_DUTY_SCHEDULE
GO
ALTER TABLE TB_ETMS_DUTY_RULE_ITEM ADD CONSTRAINT FK3B757BE62196393D FOREIGN KEY (GROUP_ID) REFERENCES TB_ETMS_BASE_GROUP
GO
ALTER TABLE TB_ETMS_DUTY_SCHEDULE ADD CONSTRAINT FK8180C327A3F981CF FOREIGN KEY (RU_ID) REFERENCES TB_ETMS_DUTY_SCHEDULE_RULE
GO
ALTER TABLE TB_ETMS_DUTY_SCHEDULE_RULE ADD CONSTRAINT FK777E6D14923333B0 FOREIGN KEY (DP_ID) REFERENCES TB_ETMS_BASE_DEPT
GO
ALTER TABLE TB_ETMS_DUTY_STAFF_ON_DUTY ADD CONSTRAINT FKC589EC47E014A937 FOREIGN KEY (DU_M_ID) REFERENCES TB_ETMS_DUTY_DUTY
GO
ALTER TABLE TB_ETMS_DUTY_STAFF_ON_DUTY ADD CONSTRAINT FKC589EC47E01934ED FOREIGN KEY (DU_W_ID) REFERENCES TB_ETMS_DUTY_DUTY
GO
ALTER TABLE TB_ETMS_DUTY_WARNING ADD CONSTRAINT FK8A9B2D0C6D138403 FOREIGN KEY (OP_ID) REFERENCES TB_ETMS_BASE_OPERATION
GO
ALTER TABLE TB_ETMS_DUTY_WARNING ADD CONSTRAINT FK8A9B2D0C48981CAF FOREIGN KEY (WARN_TYPE) REFERENCES TB_ETMS_BASE_PARA_DTL
GO
ALTER TABLE TB_ETMS_REPAIR_CARD ADD CONSTRAINT FKA4B9D389A5F25A71 FOREIGN KEY (CELL_ID) REFERENCES TB_ETMS_REPAIR_CYCLE_CELL
GO
ALTER TABLE TB_ETMS_REPAIR_CARD ADD CONSTRAINT FKA4B9D389C3E9C9 FOREIGN KEY (PERIOD_ID) REFERENCES TB_ETMS_REPAIR_PERIOD
GO
ALTER TABLE TB_ETMS_REPAIR_CYCLE ADD CONSTRAINT FKF28B4F8DE926BB57 FOREIGN KEY (DEPT_ID) REFERENCES TB_ETMS_BASE_DEPT
GO
ALTER TABLE TB_ETMS_REPAIR_CYCLE_CELL ADD CONSTRAINT FKB132A2D4D1F6726B FOREIGN KEY (CYCLE_ID) REFERENCES TB_ETMS_REPAIR_CYCLE
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD ADD CONSTRAINT FK775D8A8A2196393D FOREIGN KEY (GROUP_ID) REFERENCES TB_ETMS_BASE_GROUP
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_ITEM ADD CONSTRAINT FK871AFA8D65ED329 FOREIGN KEY (CARD_ID) REFERENCES TB_ETMS_REPAIR_CARD
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_ITEM ADD CONSTRAINT FK871AFA81D999FC9 FOREIGN KEY (RECORD_ID) REFERENCES TB_ETMS_REPAIR_RECORD
GO
ALTER TABLE TB_ETMS_REPT_BROAD_BY_TIME ADD CONSTRAINT FKE6E43D496D138403 FOREIGN KEY (OP_ID) REFERENCES TB_ETMS_BASE_OPERATION
GO
ALTER TABLE TB_SEC_DEPT_PER ADD CONSTRAINT FK9A3FB282923333B0 FOREIGN KEY (DP_ID) REFERENCES TB_ETMS_BASE_DEPT
GO
ALTER TABLE TB_SEC_DEPT_PER ADD CONSTRAINT FK9A3FB2822AC41FC4 FOREIGN KEY (EMP_ID) REFERENCES TB_ETMS_BASE_PERSON
GO
ALTER TABLE TB_SEC_PRI_ASS ADD CONSTRAINT FK95876AAA2AC41FC4 FOREIGN KEY (EMP_ID) REFERENCES TB_ETMS_BASE_PERSON
GO
ALTER TABLE TB_SEC_PRI_ASS ADD CONSTRAINT FK95876AAA41BD19CD FOREIGN KEY (ROLE_ID) REFERENCES TB_SEC_ROLE
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_EQUIP ADD CONSTRAINT FK58AC63B26650F9D FOREIGN KEY (EQUIP_ID) REFERENCES TB_ETMS_BASE_EQUIP
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_EQUIP ADD CONSTRAINT FK58AC63BB614230C FOREIGN KEY (RECORD_ITEM_ID) REFERENCES TB_ETMS_REPAIR_RECORD_ITEM
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_PERSON ADD CONSTRAINT FKBDE8FEAAAB10E617 FOREIGN KEY (PERSON_ID) REFERENCES TB_ETMS_BASE_PERSON
GO
ALTER TABLE TB_ETMS_REPAIR_RECORD_PERSON ADD CONSTRAINT FKBDE8FEAAB614230C FOREIGN KEY (RECORD_ITEM_ID) REFERENCES TB_ETMS_REPAIR_RECORD_ITEM
GO
 